matlabDoc = { 'mdcs' : 'http://www.mathworks.com/help/mdce/',
              'mps'  : 'http://www.mathworks.com/help/mps/',
              'matlab' : 'https://www.mathworks.com/help/matlab/index.html', 
              'simulink' : 'https://www.mathworks.com/help/simulink/index.html',
              'pct' : 'https://www.mathworks.com/help/distcomp/index.html', 
              'curve fitting toolbox' : 'https://www.mathworks.com/help/curvefit/index.html',
              'global optimization toolbox' : 'https://www.mathworks.com/help/gads/index.html', 
              'model-based calibration toolbox' : 'https://www.mathworks.com/help/mbc/index.html', 
              'Statistics and Machine Learning Toolbox' : 'https://www.mathworks.com/help/stats/index.html', 
              'Neural Network Toolbox' : 'https://www.mathworks.com/help/nnet/index.html', 
              'Optimization Toolbox' : 'https://www.mathworks.com/help/optim/index.html', 
              'Partial Differential Equation Toolbox' : 'https://www.mathworks.com/help/pde/index.html', 
              'Symbolic Math Toolbox' : 'https://www.mathworks.com/help/symbolic/index.html',
              'Aerospace Toolbox' : 'https://www.mathworks.com/help/aerotbx/index.html', 
              'Automated Driving System Toolbox' : 'https://www.mathworks.com/help/driving/index.html', 
              'Control System Toolbox' : 'https://www.mathworks.com/help/control/index.html',
              'Fuzzy Logic Toolbox' : 'https://www.mathworks.com/help/fuzzy/index.html', 
              'Model Predictive Control Toolbox' : 'https://www.mathworks.com/help/mpc/index.html', 
              'Robotics System Toolbox' : 'https://www.mathworks.com/help/robotics/index.html',
              'Robust Control Toolbox' : 'https://www.mathworks.com/help/robust/index.html', 
              'System Identification Toolbox' : 'https://www.mathworks.com/help/ident/index.html', 
              'Antenna Toolbox' : 'https://www.mathworks.com/help/antenna/index.html',
              'Audio System Toolbox' : 'https://www.mathworks.com/help/audio/index.html', 
              'Communications System Toolbox' : 'https://www.mathworks.com/help/comm/index.html', 
              'DSP System Toolbox' : 'https://www.mathworks.com/help/dsp/index.html',
              'LTE System Toolbox' : 'https://www.mathworks.com/help/lte/index.html', 
              'Phased Array System Toolbox' : 'https://www.mathworks.com/help/phased/index.html', 
              'RF Toolbox' : 'https://www.mathworks.com/help/rf/index.html',
              'Signal Processing Toolbox' : 'https://www.mathworks.com/help/signal/index.html', 
              'Wavelet Toolbox' : 'https://www.mathworks.com/help/wavelet/index.html', 
              'WLAN System Toolbox' : 'https://www.mathworks.com/help/wlan/index.html',
              'Computer Vision System Toolbox' : 'https://www.mathworks.com/help/vision/index.html', 
              'Image Acquisition Toolbox' : 'https://www.mathworks.com/help/imaq/index.html',
              'Image Processing Toolbox' : 'https://www.mathworks.com/help/images/index.html', 
              'Mapping Toolbox' : 'https://www.mathworks.com/help/map/index.html', 
              'Data Acquisition Toolbox' : 'https://www.mathworks.com/help/daq/index.html',
              'Instrument Control Toolbox' : 'https://www.mathworks.com/help/instrument/index.html', 
              'OPC Toolbox' : 'https://www.mathworks.com/help/opc/index.html',
              'Vehicle Network Toolbox' : 'https://www.mathworks.com/help/vnt/index.html', 
              'Database Toolbox' : 'https://www.mathworks.com/help/database/index.html', 
              'Datafeed Toolbox' : 'https://www.mathworks.com/help/datafeed/index.html',
              'Econometrics Toolbox' : 'https://www.mathworks.com/help/econ/index.html', 
              'Financial Instruments Toolbox' : 'https://www.mathworks.com/help/fininst/index.html', 
              'Financial Toolbox' : 'https://www.mathworks.com/help/finance/index.html',
              'Risk Management Toolbox' : 'https://www.mathworks.com/help/risk/index.html', 
              'Spreadsheet Link' : 'https://www.mathworks.com/help/exlink/index.html', 
              'Trading Toolbox' : 'https://www.mathworks.com/help/trading/index.html',
              'Bioinformatics Toolbox' : 'https://www.mathworks.com/help/bioinfo/index.html', 
              'SimBiology' : 'https://www.mathworks.com/help/simbio/index.html', 
              'Filter Design HDL Coder' : 'https://www.mathworks.com/help/hdlfilter/index.html',
              'Fixed-Point Designer' : 'https://www.mathworks.com/help/fixedpoint/index.html', 
              'HDL Coder' : 'https://www.mathworks.com/help/hdlcoder/index.html', 
              'HDL Verifier' : 'https://www.mathworks.com/help/hdlverifier/index.html',
              'MATLAB Coder' : 'https://www.mathworks.com/help/coder/index.html', 
              'Vision HDL Toolbox' : 'https://www.mathworks.com/help/visionhdl/index.html', 
              'MATLAB Compiler' : 'https://www.mathworks.com/help/compiler/index.html',
              'MATLAB Compiler SDK' : 'https://www.mathworks.com/help/compiler_sdk/index.html', 
              'Database Toolbox' : 'https://www.mathworks.com/help/database/index.html',
              'MATLAB Report Generator' : 'https://www.mathworks.com/help/rptgen/index.html', 
              'SimEvents' : 'https://www.mathworks.com/help/simevents/index.html', 
              'Stateflow' : 'https://www.mathworks.com/help/stateflow/index.html',
              'Simscape' : 'https://www.mathworks.com/help/physmod/simscape/index.html', 
              'Simscape Driveline' : 'https://www.mathworks.com/help/physmod/sdl/index.html', 
              'Simscape Electronics' : 'https://www.mathworks.com/help/physmod/elec/index.html',
              'Simscape Fluids' : 'https://www.mathworks.com/help/physmod/hydro/index.html', 
              'Simscape Multibody' : 'https://www.mathworks.com/help/physmod/sm/index.html', 
              'Simscape Multibody Link' : 'https://www.mathworks.com/help/physmod/smlink/index.html',
              'Simscape Power Systems' : 'https://www.mathworks.com/help/physmod/sps/index.html', 
              'Aerospace Blockset' : 'https://www.mathworks.com/help/aeroblks/index.html', 
              'Powertrain Blockset' : 'https://www.mathworks.com/help/autoblks/index.html',
              'Robotics System Toolbox' : 'https://www.mathworks.com/help/robotics/index.html', 
              'Simulink Control Design' : 'https://www.mathworks.com/help/slcontrol/index.html', 
              'Simulink Design Optimization' : 'https://www.mathworks.com/help/sldo/index.html',
              'DSP System Toolbox' : 'https://www.mathworks.com/help/dsp/index.html', 
              'Phased Array System Toolbox' : 'https://www.mathworks.com/help/phased/index.html', 
              'RF Blockset' : 'https://www.mathworks.com/help/simrf/index.html',
              'Embedded Coder' : 'https://www.mathworks.com/help/ecoder/index.html', 
              'Fixed-Point Designer' : 'https://www.mathworks.com/help/fixedpoint/index.html', 
              'HDL Coder' : 'https://www.mathworks.com/help/hdlcoder/index.html',
              'Simulink Coder' : 'https://www.mathworks.com/help/rtw/index.html', 
              'Simulink PLC Coder' : 'https://www.mathworks.com/help/plccoder/index.html', 
              'Vision HDL Toolbox' : 'https://www.mathworks.com/help/visionhdl/index.html',
              'Simulink Desktop Real-Time' : 'https://www.mathworks.com/help/sldrt/index.html', 
              'Simulink Real-Time' : 'https://www.mathworks.com/help/xpc/index.html', 
              'Polyspace Bug Finder' : 'https://www.mathworks.com/help/bugfinder/index.html', 
              'Polyspace Code Prover' : 'https://www.mathworks.com/help/codeprover/index.html', 
              'Simulink Code Inspector' : 'https://www.mathworks.com/help/slci/index.html',                
              'Simulink Design Verifier' : 'https://www.mathworks.com/help/sldv/index.html', 
              'Simulink Test' : 'https://www.mathworks.com/help/sltest/index.html', 
              'Simulink Verification and Validation' : 'https://www.mathworks.com/help/slvnv/index.html',
              'Simulink 3D Animation' : 'https://www.mathworks.com/help/sl3d/index.html', 
              'Simulink Report Generator' : 'https://www.mathworks.com/help/rptgenext/index.html' }
              
matlabDoc = {k.lower(): v for k, v in matlabDoc.items()}


toolboxList = { 'matlab' : 'matlab', 'simulink' : 'simulink', 'mdcs' : '',
                'mps' : 'matlab_production_server', 'pct' : 'distrib_computing_toolbox', 'curve fitting toolbox' : 'curve_fitting_toolbox',
                'global optimization toolbox' : 'gads_toolbox', 'model-based calibration toolbox' : 'mbc_toolbox', 
                'Statistics and Machine Learning Toolbox' : 'statistics_toolbox', 'Neural Network Toolbox' : 'neural_network_toolbox', 
                'Optimization Toolbox' : 'optimization_toolbox', 'Partial Differential Equation Toolbox' : 'pde_toolbox', 'Symbolic Math Toolbox' : 'symbolic_toolbox',
                'Aerospace Toolbox' : 'aerospace_toolbox', 'Automated Driving System Toolbox' : '', 'Control System Toolbox' : 'control_toolbox',
                'Fuzzy Logic Toolbox' : 'fuzzy_toolbox', 'Model Predictive Control Toolbox' : 'mpc_toolbox', 'Robotics System Toolbox' : '',
                'Robust Control Toolbox' : 'robust_toolbox', 'System Identification Toolbox' : 'identification_toolbox', 'Antenna Toolbox' : 'antenna_toolbox',
                'Audio System Toolbox' : 'audio_system_toolbox', 'Communications System Toolbox' : 'communcation_toolbox', 'DSP System Toolbox' : '',
                'LTE System Toolbox' : 'lte_toolbox', 'Phased Array System Toolbox' : 'phased_array_system_toolbox', 'RF Toolbox' : 'rf_toolbox',
                'Signal Processing Toolbox' : 'signal_toolbox', 'Wavelet Toolbox' : 'wavelet_toolbox', 'WLAN System Toolbox' : 'wlan_system_toolbox',
                'Automated Driving System Toolbox' : '', 'Computer Vision System Toolbox' : 'video_and_image_blockset', 'Image Acquisition Toolbox' : 'image_acquisition_toolbox',
                'Image Processing Toolbox' : 'image_toolbox', 'Mapping Toolbox' : 'map_toolbox', 'Data Acquisition Toolbox' : 'data_acq_toolbox',
                'Instrument Control Toolbox' : 'instr_control_toolbox', 'OPC Toolbox' : 'opc_toolbox',
                'Vehicle Network Toolbox' : 'vehicle_network_toolbox', 'Database Toolbox' : 'database_toolbox', 'Datafeed Toolbox' : 'datafeed_toolbox',
                'Econometrics Toolbox' : 'econometrics_toolbox', 'Financial Instruments Toolbox' : 'fin_instruments_toolbox', 'Financial Toolbox' : 'financial_toolbox',
                'Risk Management Toolbox' : 'risk_management_toolbox', 'Spreadsheet Link' : 'excel_link', 'Trading Toolbox' : 'trading_toolbox',
                'Bioinformatics Toolbox' : 'bioinformatics_toolbox', 'SimBiology' : 'simbiology', 'Filter Design HDL Coder' : 'filter_design_hdl_coder',
                'Fixed-Point Designer' : 'fixed_point_toolbox', 'HDL Coder' : 'simulink_hdl_coder', 'HDL Verifier' : 'eda_simulator_link',
                'MATLAB Coder' : 'matlab_coder', 'Vision HDL Toolbox' : 'vision_hdl_toolbox', 'MATLAB Compiler' : 'compiler',
                'MATLAB Compiler SDK' : 'matlab_builder_for_java', 'Database Toolbox' : '',
                'MATLAB Report Generator' : 'matlab_report_gen', 'SimEvents' : 'simevents', 'Stateflow' : 'stateflow',
                'Simscape' : 'simscape', 'Simscape Driveline' : 'simdriveline', 'Simscape Electronics' : 'simslectronics',
                'Simscape Fluids' : 'simhydraulics', 'Simscape Multibody' : 'simmachanics', 'Simscape Multibody Link' : '',
                'Simscape Power Systems' : 'power_system_blocks', 'Aerospace Blockset' : 'aerospace_blockset', 'Powertrain Blockset' : '',
                'Robotics System Toolbox' : 'robotics_system_toolbox', 'Simulink Control Design' : 'simulink_control_design', 'Simulink Design Optimization' : 'simulink_design_optim',
                'DSP System Toolbox' : 'signal_blocks', 'Phased Array System Toolbox' : '', 'RF Blockset' : '',
                'Embedded Coder' : 'raw_embedded_coder', 'Fixed-Point Designer' : '', 'HDL Coder' : 'simulink_hdl_coder',
                'Simulink Coder' : 'real-time_workshop', 'Simulink PLC Coder' : 'simulink_plc_coder', 'Vision HDL Toolbox' : '',
                'Simulink Desktop Real-Time' : 'real-time_win_target', 'Simulink Real-Time' : 'xpc_target', 'HDL Verifier' : 'eda_simulator_link',
                'Polyspace Bug Finder' : 'polyspace_bug_finder_engine', 'Polyspace Code Prover' : 'polyspace_server_c_cpp', 'Simulink Code Inspector' : 'simulink_code_inspector',
                'Simulink Design Verifier' : 'simulink_design_verifier', 'Simulink Test' : 'simulink_test', 'Simulink Verification and Validation' : 'sl_verification_validation',
                'Simulink 3D Animation' : 'virtual_reality_toolbox', 'Simulink Report Generator' : 'simulink_report_gen'}

toolboxList = {k.lower(): v for k, v in toolboxList.items()}

